export const data = {
  sources: [
    {
      id: 1,
      name: "meduza",
    },
    {
      id: 6,
      name: "3dnews",
    },
    {
      id: 7,
      name: "nytimes",
    },
    {
      id: 8,
      name: "forbes",
    },
    {
      id: 9,
      name: "igromania",
    },
    {
      id: 10,
      name: "buro237",
    },
    {
      id: 11,
      name: "rusvesna",
    },
    {
      id: 12,
      name: "7ya",
    },
    {
      id: 14,
      name: "aif",
    },
    {
      id: 15,
      name: "gazetaru",
    },
    {
      id: 16,
      name: "karpov.courses",
    },
  ],
  categories: [
    {
      id: 1,
      name: "tech",
    },
    {
      id: 2,
      name: "sport",
    },
    {
      id: 3,
      name: "fashion",
    },
    {
      id: 4,
      name: "politics",
    },
    {
      id: 5,
      name: "other",
    },
    {
      id: 6,
      name: "karpov.courses",
    },
  ],
  items: [
    {
      id: 425313,
      lang: "ru",
      date: "Sun Oct 08 2023 18:09:51 GMT+0300 (Moscow Standard Time)",
      title: "Издателя The Lord of the Rings Gollum обвинили в написании извинений с ChatGPT",
      description: "",
      image: "https://newcdn.igromania.ru/articles/pics/tmp/images/2023/10/8/bd2254d9-b102-4de1-ac55-5d3f20058306.png",
      source_id: 9,
      category_id: 1,
    },
    {
      id: 425312,
      lang: "ru",
      date: "Sun Oct 08 2023 18:01:18 GMT+0300 (Moscow Standard Time)",
      title: "Daily Mail: Саудовская Аравия примет чемпионат мира по футболу 2034 года",
      description: "Выборы страны для его проведения в мае 2024 года будут формальностью, утверждают источники.",
      image: "https://aif-s3.aif.ru/images/034/243/fd886202b8fec57d9f0d2ea461a516f3.jpg",
      source_id: 14,
      category_id: 2,
    },
    {
      id: 425348,
      lang: "ru",
      date: "Sun Oct 08 2023 18:01:01 GMT+0300 (Moscow Standard Time)",
      title: "Установлено, какие женщины чаще испытывают вагинальный оргазм",
      description:
        "Ученые из Университета Нью-Мексико установили, что женщины, которые предпочитают более глубокую стимуляцию, с большей вероятностью испытывают вагинальный, но не клиторальный оргазм. Результаты исследования были представлены в журнале The ...",
      image: "https://img.gazeta.ru/files3/848/17052848/shutterstock_1103801354-pic905-895x505-33480.jpg",
      source_id: 15,
      category_id: 1,
    },
    {
      id: 425325,
      lang: "ru",
      date: "Sun Oct 08 2023 17:59:57 GMT+0300 (Moscow Standard Time)",
      title: "Эрдоган назвал условие для мира на Ближнем Востоке",
      description:
        "Президент Турции Реджеп Тайип Эрдоган заявил, только при условии независимости Палестины возможно обеспечить мир на Ближнем Востоке, передает ТАСС. Обеспечение стабильного мира на Ближнем Востоке возможно только при окончательном ...",
      image: "https://img.gazeta.ru/files3/323/16166323/2023-01-18T105606Z_1411367087_RC2YSY9C5S8L_RTRMADP_3_TURKEY-ELECTION-ERDOGAN-pic905-895x505-63401.jpg",
      source_id: 15,
      category_id: 4,
    },
    {
      id: 425317,
      lang: "ru",
      date: "Sun Oct 08 2023 17:56:52 GMT+0300 (Moscow Standard Time)",
      title: "Ученые усомнились в авторстве Пифагора в знаменитой теореме",
      description: "Это может стать самым древним в мире известным случаем плагиата.",
      image: "https://aif-s3.aif.ru/images/034/243/aa2350f492ca75a8bf5719f913328226.jpg",
      source_id: 14,
      category_id: 4,
    },
    {
      id: 425320,
      lang: "ru",
      date: "Sun Oct 08 2023 17:51:35 GMT+0300 (Moscow Standard Time)",
      title: "Сын Трампа сравнил конфликт на Украине с войной в Израиле",
      description: "Трамп-младший удивлен большим количеством видео в Сети о происходящем в Израиле.",
      image: "https://aif-s3.aif.ru/images/034/243/722939f94aa7fa8d3a9f26fdadbac0be.jpg",
      source_id: 14,
      category_id: 5,
    },
    {
      id: 425349,
      lang: "ru",
      date: "Sun Oct 08 2023 17:47:25 GMT+0300 (Moscow Standard Time)",
      title: "Установлено, какие мужья обсуждают финансовые проблемы в семье",
      description:
        "Ученые из Обернского университет (США) установили, что счастливые мужья более открыто и эффективно обсуждали финансовые проблемы. Результаты исследования были опубликованы в журнале Journal of Social and Personal Relationships. Некоторые ...",
      image: "https://img.gazeta.ru/files3/972/17258972/shutterstock_2145836807-pic905-895x505-33172.jpg",
      source_id: 15,
      category_id: 1,
    },
    {
      id: 425327,
      lang: "ru",
      date: "Sun Oct 08 2023 17:47:03 GMT+0300 (Moscow Standard Time)",
      title: "Посол Израиля заявила, что еще не время для посредничества в конфликте с Палестиной",
      description:
        "Посол Израиля в Турции Ирит Лилиан заявила, что еще не время для посредничества в конфликте между ее страной и Палестиной, передает телеканал Haber Global. Посредничество осуществляется в другое время.  Мы хотим, чтобы тишина и ...",
      image: "https://img.gazeta.ru/files3/958/12784958/RIAN_5640272.HR-pic905-895x505-91865.jpg",
      source_id: 15,
      category_id: 4,
    },
    {
      id: 425322,
      lang: "ru",
      date: "Sun Oct 08 2023 17:41:39 GMT+0300 (Moscow Standard Time)",
      title: "Египетские переговорщики не смогли убедить Палестину отпустить заложников",
      description: "Число оказавшихся у движения ХАМАС заложников неизвестно.",
      image: "https://aif-s3.aif.ru/images/034/243/706a6e82bcf39a4d37370df88f135960.JPG",
      source_id: 14,
      category_id: 4,
    },
    {
      id: 425329,
      lang: "ru",
      date: "Sun Oct 08 2023 17:41:01 GMT+0300 (Moscow Standard Time)",
      title: "Эрдоган обсудит с правительством меры по решению конфликта в Израиля",
      description:
        "Турецкий президент Реджеп Тайип Эрдоган обсудит 9 октября с правительством шаги по урегулированию ситуации в Израиле. Об этом сообщает РИА Новости со ссылкой на представителя в администрации турецкого лидера. Завтра в резиденции ...",
      image:
        "https://img.gazeta.ru/files3/124/17608124/2023-09-06T141547Z_1601247681_RC2233AFAET4_RTRMADP_3_TURKEY-ECONOMY-PROGRAMME-ERDOGAN-pic905-895x505-92310.jpg",
      source_id: 15,
      category_id: 4,
    },
    {
      id: 425318,
      lang: "ru",
      date: "Sun Oct 08 2023 17:35:30 GMT+0300 (Moscow Standard Time)",
      title: "Координатор интимных сцен рассказала о работе над Baldurs Gate 3",
      description: "",
      image: "https://newcdn.igromania.ru/articles/pics/tmp/images/2023/10/8/b3d6bc4f-f90f-4a2d-9bb6-25c250144ebd.png",
      source_id: 9,
      category_id: 1,
    },
    {
      id: 425323,
      lang: "ru",
      date: "Sun Oct 08 2023 17:34:34 GMT+0300 (Moscow Standard Time)",
      title: "МакSим рассказала, что занимается спортом после лечения от алкоголизма",
      description: "Певица также регулярно окунается в ледяную купель.",
      image: "https://aif-s3.aif.ru/images/034/243/2edf0118cbd5209ff150adba615ddfc6.jpg",
      source_id: 14,
      category_id: 5,
    },
    {
      id: 425350,
      lang: "ru",
      date: "Sun Oct 08 2023 17:33:45 GMT+0300 (Moscow Standard Time)",
      title: "Установлено, в каком возрасте люди чаще занимаются сексом ",
      description:
        "Как мужчины, так и женщины наиболее сексуально активны в возрасте 25-29 лет, сообщили специалисты компании Sexual Alpha, которые провели исследование. Так, 74,4% мужчин и 74,3% женщин сообщили по крайней мере об одном сексуальном контакте ...",
      image: "https://img.gazeta.ru/files3/530/17172530/sexstoccck-pic905-895x505-79914.jpg",
      source_id: 15,
      category_id: 1,
    },
    {
      id: 425331,
      lang: "ru",
      date: "Sun Oct 08 2023 17:33:33 GMT+0300 (Moscow Standard Time)",
      title: "США и Британия подталкивают ЕС к приему Украины в блок",
      description:
        "США и Великобритания 'подталкивают' Евросоюз к расширению, чтобы обеспечить дополнительное финансирование Украины. Об этом сообщила The Telegraph со ссылкой на источники. По их информации, Штаты Британия на фоне нерешительного ...",
      image: "https://img.gazeta.ru/files3/832/16675832/20220713_gaf_u39_1751-pic905-895x505-76977.jpg",
      source_id: 15,
      category_id: 4,
    },
    {
      id: 425324,
      lang: "ru",
      date: "Sun Oct 08 2023 17:33:07 GMT+0300 (Moscow Standard Time)",
      title: "Минобороны предложило изменить статус Северного флота",
      description: "Это необходимо для создания Ленинградского военного округа.",
      image: "https://aif-s3.aif.ru/images/034/243/302e6344aedba55d23bfff7a8767f4ac.JPG",
      source_id: 14,
      category_id: 5,
    },
    {
      id: 425310,
      lang: "ru",
      date: "Sun Oct 08 2023 17:29:48 GMT+0300 (Moscow Standard Time)",
      title: "Минэкономразвития посоветовало россиянам отказаться от поездок в Израиль",
      description:
        "Минэкономразвития посоветовало российским туристам воздержаться от поездок в Израиль. Тем, кто уже находится в стране, следует быть осторожными и следить за сообщениями местных властей, заявило министерство. Туроператорам рекомендовано остановить продажу туров в Израиль. В стране сейчас находятся около 100 организованных туристов",
      image: "",
      source_id: 8,
      category_id: 5,
    },
    {
      id: 425333,
      lang: "ru",
      date: "Sun Oct 08 2023 17:24:49 GMT+0300 (Moscow Standard Time)",
      title: "Нетаньяху провел переговоры с Шольцем, Зеленским, Мелони и Сунаком",
      description:
        "Премьер-министр Израиля Биньямин Нетаньяху провел телефонные переговоры с канцлером Германии Олафом Шольцем, президентом Украины Владимиром Зеленским, премьер-министром Италии Джорджей Мелони и премьер-министром Великобритании Риши ...",
      image:
        "https://img.gazeta.ru/files3/230/13617230/2021-05-19T110534Z_566216546_RC2XIN931PI2_RTRMADP_3_ISRAEL-PALESTINIANS-NETANYAHU-pic905-895x505-14185.jpg",
      source_id: 15,
      category_id: 4,
    },
    {
      id: 425314,
      lang: "ru",
      date: "Sun Oct 08 2023 17:23:19 GMT+0300 (Moscow Standard Time)",
      title: "Фанаты Валиевой разместили ролик в поддержку фигуристки на Таймс-сквер",
      description:
        "Болельщики российской фигуристки Камилы Валиевой, чье дело о нарушении антидопинговых правил рассматривается в Спортивном арбитражном суде (CAS), разместили ролик в ее поддержку на рекламных экранах площади Таймс-сквер в Нью-Йорке",
      image: "",
      source_id: 8,
      category_id: 5,
    },
    {
      id: 425346,
      lang: "ru",
      date: "Sun Oct 08 2023 17:19:59 GMT+0300 (Moscow Standard Time)",
      title: "Компания OnePlus выпустит в 2024 году новые умные часы с круглым экраном",
      description:
        "Компания OnePlus намерена в 2024 году представить фирменные умные часы с круглым циферблатом. Об этом сообщает портал Android Authority со ссылкой на инсайдера Макса Джамбора. В портфолио бренда уже есть два пары умных часов: OnePlus ...",
      image: "http://img.gazeta.ru/files3/857/17702857/55-pic905-895x505-76580.jpg",
      source_id: 15,
      category_id: 1,
    },
    {
      id: 425308,
      lang: "ru",
      date: "Sun Oct 08 2023 17:15:00 GMT+0300 (Moscow Standard Time)",
      title: "Захарян идет в бой: 'Реал Сосьедад' сражается с мадридским 'Атлетико'. LIVE",
      description:
        "'Реал Сосьедад', за который выступает российский полузащитник Арсен Захарян, в выездном поединке играет против мадридского 'Атлетико' в девятом туре чемпионата Испании. 'Газета.Ru' ведет текстовую онлайн-трансляцию встречи.",
      image: "https://img.gazeta.ru/files3/486/17483486/10-pic905-895x505-69216.jpg",
      source_id: 15,
      category_id: 2,
    },
  ],
};
